### ISSUE TITLE
Week3 (2022.01.03~2022.01.09)

### ISSUE THREAD

**Issue by lysuk96** [Algo2022/Code_Study#10]
- 문제출제자 : 영석

### 스택/큐, DP
- [기능개발](https://programmers.co.kr/learn/courses/30/lessons/42586?language=python3)
- [프린터](https://programmers.co.kr/learn/courses/30/lessons/42587)
- [다리를 지나는 트럭](https://programmers.co.kr/learn/courses/30/lessons/42583)
- [정수 삼각형](https://programmers.co.kr/learn/courses/30/lessons/43105?language=python3)
- [등굣길](https://programmers.co.kr/learn/courses/30/lessons/42898?language=python3)

**Comment by k12ms26** [comment]
- [민선] 정수 삼각형, 등굣길 대신 [LCS](https://www.acmicpc.net/problem/9251), [동전 1](https://www.acmicpc.net/problem/2293) 풀 예정
