### ISSUE TITLE
Week4 (2022.01.10~2022.01.17)

### ISSUE THREAD

**Issue by p51lee** [Algo2022/Code_Study#18]
출제 이강욱

## 이분탐색
* [입국심사](https://programmers.co.kr/learn/courses/30/lessons/43238)
* [징검다리](https://programmers.co.kr/learn/courses/30/lessons/43236)

## 그래프
* [가장 먼 노드](https://programmers.co.kr/learn/courses/30/lessons/49189)
* [순위](https://programmers.co.kr/learn/courses/30/lessons/49191)

## 동적계획법
* [도둑질](https://programmers.co.kr/learn/courses/30/lessons/42897)

**Comment by k12ms26** [comment]
[민선] 도둑질 대신 [타일 채우기](https://www.acmicpc.net/problem/2133) 풀 예정
